name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: weather-app
        run: npm install

      - name: Build
        working-directory: weather-app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -R weather-app/dist/* gh-pages/
          cd gh-pages
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy via GitHub Actions"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
